### ISSUE TITLE
Is a IANA YANG module a better home for the TLS parameters?

### ISSUE THREAD

**Issue by sidsharma** [netconf-wg/tls-client-server#1]
This is rather a question than an issue, maybe.

Given that IANA maintains the TLS parameters at https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml, would it not be better for that content to come from something like iana-tls[-parameters].yang rather than an IETF maintained YANG module?

**Comment by kwatsen** [comment]
I will relay your message to the "netconf" mailing list: https://www.ietf.org/mailman/listinfo/netconf.

Closing this "issue" since the WG doesn't officially use the GitHub issue tracker...

K.

**Comment by sidsharma** [comment]
Thank you, the same comment applies for ssh-client-server https://www.iana.org/assignments/ssh-parameters/ssh-parameters.xhtml

**Comment by kwatsen** [comment]
I posted the message here: https://mailarchive.ietf.org/arch/msg/netconf/tVaiqDpAr64MpCx0bE_WzaAawbE

I had already extended the comment to SSH.

IDK if you're just pointing out an optimization, or if you have strong interest in this work, but you might consider joining the discussion on the netconf list....
